version: "3.0"
services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION}
    volumes:
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./data:/usr/share/elasticsearch/data
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"
      - "thread_pool.write.queue_size=1000"
    user: 1000:1000
    networks:
      - elastic-net
    ports:
      - 9200:9200  
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 3072M
    healthcheck:
      test:
        - CMD-SHELL
        - 'curl --user ${ES_HEALTH_USER}:${ES_HEALTH_PASSWORD} -XGET http://localhost:9200/_cluster/health || exit 1'
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:${ELASTIC_VERSION}
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    environment:
      - SERVERNAME=kibana
      - KIBANA_ENCRYPTION_KEY=${KIBANA_ENCRYPTION_KEY}
      - ELASTICSEARCH_USERNAME=${KIBANA_SYSTEM_USER}
      - ELASTICSEARCH_PASSWORD=${KIBANA_SYSTEM_PASSWORD}
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - KIBANA_PUBLIC_URL=${KIBANA_PUBLIC_URL}
    user: 1000:1000
    networks:
      - elastic-net
      - traefik-public
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    healthcheck:
      test:
        - CMD-SHELL
        - 'curl -XGET http://localhost:5601/login || exit 1'
    labels:
      - traefik.enable=true
      - 'traefik.docker.network=traefik-public'
      - 'traefik.http.services.kibana.loadbalancer.server.port=5601'
      - 'traefik.http.routers.kibana.rule=Host(`${TRAEFIK_KIBANA_HOST}`)'
      - 'traefik.http.routers.kibana.entrypoints=websecure'
      - 'traefik.http.routers.kibana.tls.certresolver=letsencrypt'
      - 'traefik.http.routers.kibana.middlewares=homeonly@docker'

networks:
  elastic-net:
    driver: bridge
    name: elastic-net
  traefik-public:
    external: true
    name: traefik-public
